- !<Qubit>
  name: qubit
  int_freq: 1.773565E+08
  lo_name: lo_qubit
  mixer_offsets:
    I: 0.0070546144735999395
    Q: 0.005051575438119471
    G: 0.2041032314300537
    P: 0.18648304939270022
  operations:
    qubit_gaussian_short_pi_pulse: !<GaussianPulse>
      name: qubit_gaussian_short_pi_pulse
      I_ampx: 1.13
      Q_ampx: -0.028
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 30
      total_I_ampx: 0.22599999999999998
      total_length: 120
    qubit_gaussian_short_pi2_pulse: !<GaussianPulse>
      name: qubit_gaussian_short_pi2_pulse
      I_ampx: 0.56
      Q_ampx: -0.028
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 30
      total_I_ampx: 0.11200000000000002
      total_length: 120
    qubit_gaussian_sel_pi_pulse: !<GaussianPulse>
      name: qubit_gaussian_sel_pi_pulse
      I_ampx: 0.042
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 800
      total_I_ampx: 0.008400000000000001
      total_length: 3200
    qubit_gaussian_sel_pi2_pulse: !<GaussianPulse>
      name: qubit_gaussian_sel_pi2_pulse
      I_ampx: 0.021
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 800
      total_I_ampx: 0.004200000000000001
      total_length: 3200
    qubit_grape_pi_pulse: !<NumericalPulse>
      name: qubit_grape_pi_pulse
      I_ampx: 374
      Q_ampx: 374
      digital_marker: null
      length: 400
      pad: 400
      path: C:\Users\qcrew\Documents\yabba\waves\c_coh_1.npz
      total_I_ampx: 74.8
      total_Q_ampx: 74.8
      total_length: 800
  ports:
    I: 1
    Q: 2
  rf_switch: null
  rf_switch_on: false
- !<Qubit>
  name: qubitEF
  int_freq: 1.739000E+06
  lo_name: lo_qubit
  mixer_offsets:
    I: 0.0071526846615597595
    Q: 0.005089394142851233
    G: 0.18711491525173193
    P: -0.10331471562385564
  operations:
    qubitEF_gaussian_short_pi_pulse: !<GaussianPulse>
      name: qubitEF_gaussian_short_pi_pulse
      I_ampx: 0.694
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 20
      total_I_ampx: 0.1388
      total_length: 80
  ports:
    I: 1
    Q: 2
  rf_switch: null
  rf_switch_on: false
- !<Readout>
  name: rr
  int_freq: 5.000000E+07
  lo_name: lo_rr
  mixer_offsets:
    I: 0.0
    Q: 0.0
    G: 0.17265625
    P: 0.03281250000000001
    out: -0.020806603064903846
  operations:
    rr_readout_pulse: !<ConstantReadoutPulse>
      name: rr_readout_pulse
      I_ampx: 0.3
      Q_ampx: 0.0
      digital_marker: !<DigitalWaveform>
        name: ADC_ON
        samples:
        - - 1
          - 0
      has_optimized_weights: true
      length: 1500
      pad: 900
      threshold: 0.0001440406944069628
      total_I_amp: 0.06
      total_length: 2400
      weights: C://Users//qcrew//Desktop//qcrew//qcrew//config//weights//20230801_184026_opt_weights.npz
  ports:
    I: 3
    Q: 4
    out: 1
  rf_switch: null
  rf_switch_on: false
  smearing: 0
  tof: 282
- !<Cavity>
  name: cav
  int_freq: 8.954000E+07
  lo_name: lo_cav
  mixer_offsets:
    I: 0.017144775390625002
    Q: -0.006228637695312497
    G: 0.18436107337474825
    P: 0.14532665610313417
  operations:
    cavity_gaussian_coherent_1: !<GaussianPulse>
      name: cavity_gaussian_coherent_1
      I_ampx: 1.0
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 27
      total_I_ampx: 0.2
      total_length: 108
    cavity_coherent_1: !<GaussianPulse>
      name: cavity_coherent_1
      I_ampx: 1.0
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 27
      total_I_ampx: 0.2
      total_length: 108
    cavity_coherent_1_long: !<GaussianPulse>
      name: cavity_coherent_1_long
      I_ampx: 0.515
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 52
      total_I_ampx: 0.10300000000000001
      total_length: 208
    cavity_coherent_1_longer: !<GaussianPulse>
      name: cavity_coherent_1_longer
      I_ampx: 0.335
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 80
      total_I_ampx: 0.067
      total_length: 320
    cavity_coherent_alot: !<GaussianPulse>
      name: cavity_coherent_alot
      I_ampx: 1.0
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 500
      total_I_ampx: 0.2
      total_length: 2000
  ports:
    I: 5
    Q: 6
  rf_switch: null
  rf_switch_on: false
